services:
  - type: web
    name: api-rascadores
    env: node
    rootDir: apps/api
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rascadores-db
          property: connectionString
      - key: WOMPI_INTEGRITY_SECRET
        sync: false

  - type: static
    name: pwa-rascadores
    rootDir: apps/client
    buildCommand: npm install && npm run build
    staticPublishPath: apps/client/dist/client/browser
    routes:
      - type: rewrite
        source: /**
        destination: /index.html